apiVersion: v2
name: kubevirt-cdi
description: Install the Containerized Data Importer

type: application
version: 0.2.1
appVersion: "v1.61.0"

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"
