apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary
  namespace: metallb-system
spec:
  addresses:
  - 10.1.0.248/32
  - 192.168.2.70/32
  - 192.168.2.71/32
  - 192.168.2.72/32
  - 192.168.2.73/32
