---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    eni:
      enabled: true
    k8sServiceHost: 192.168.2.70
    k8sServicePort: 6443
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 100.64.0.0/17
    routingMode: native
    socketLB:
      hostNamespaceOnly: true
    bpf:
      masquerade: true
      hostLegacyRouting: true
    l2announcements:
      enabled: false
    l7Proxy: false
    ingressController:
      enabled: false
      loadbalancerMode: shared
    externalIPs:
      enabled: true
    devices: enp11s0f1np1
    k8sClientRateLimit:
      qps: 5
      burst: 10
    operator:
      replicas: 1
    encryption:
      enabled: false
      type: wireguard
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
