apiVersion: v2
name: kubevirt-vm
description: Configure a virtual machine for use with Kubevirt

type: application
version: 0.4.10
appVersion: "0.1.0"

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"

dependencies:
- name: cloud-init
  alias: cloudinit
  version: 0.2.8
  repository: https://cloudymax.github.io/kubevirt-community-stack
  condition: cloudinit.enabled
