apiVersion: v2
name: kubevirt-vm
description: Configure a virtual machine for use with Kubevirt

type: application
version: 0.2.5
appVersion: "0.1.0"

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"
