{{ if .Values.virtualMachinePool.enabled }}
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: {{ .Values.virtualMachine.name }}
  namespace: {{ .Values.virtualMachine.namespace }}
  labels:
    kubevirt-manager.io/managed: "true"
    kubevirt.io/vmpool: {{ .Values.virtualMachine.name }}
spec:
  replicas: {{ .Values.virtualMachinePool.size }}
  selector:
    matchLabels:
      kubevirt.io/vmpool: {{ .Values.virtualMachine.name }}
      kubevirt.io/domain: {{ .Values.virtualMachine.name }}
      kubevirt-service: {{ .Values.virtualMachine.name }}
      kubevirt-manager.io/managed: "true"
  virtualMachineTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmpool: {{ .Values.virtualMachine.name }}
        kubevirt.io/domain: {{ .Values.virtualMachine.name }}
        kubevirt-service: {{ .Values.virtualMachine.name }}
        kubevirt-manager.io/managed: "true"
    spec:
      running: true
      template:
        metadata:
          creationTimestamp: null
          labels:
            kubevirt.io/vmpool: {{ .Values.virtualMachine.name }}
            kubevirt.io/domain: {{ .Values.virtualMachine.name }}
            kubevirt-service: {{ .Values.virtualMachine.name }}
            kubevirt-manager.io/managed: "true"
        spec:
          domain:
            features:
              {{- if .Values.virtualMachine.features.kvmEnabled -}}
              {{ "kvm: {}" | nindent 14 }}
              {{- end }}
              {{- if .Values.virtualMachine.features.acpiEnabled -}}
              {{ "acpi: {}" | nindent 14 }}
              {{- end }}
              {{- if .Values.virtualMachine.features.smmEnabled -}}
              {{ "smm:"  | nindent 14 -}}
              {{ "enabled: true"  | nindent 16 }}
              {{- end }}
            cpu:
              {{- if .Values.virtualMachine.machine.cpuPassthrough -}}
              {{ "model: host-passthrough" | nindent 14 }}
              {{- end }}
              sockets: 1
              cores: {{ .Values.virtualMachine.machine.vCores -}}
              {{- if .Values.virtualMachine.machine.hyperThreadingEnabled -}}
              {{- "threads: 2" | nindent 14 -}}
              {{ else }}
              {{- "threads: 1" | nindent 14 -}}
              {{- end }}
            {{- if .Values.virtualMachine.features.efiEnabled -}}
            {{- "firmware:" | nindent 12 -}}
            {{- "bootloader:" |nindent 14 -}}
            {{- "efi: {}" | nindent 16 -}}
            {{- end }}
            devices:
              {{- with .Values.virtualMachine.gpus }}
              gpus:
              {{- toYaml . | nindent 14 }}
              {{- end }}
              autoattachPodInterface: {{ .Values.virtualMachine.features.autoattachPodInterface }}
              autoattachSerialConsole: {{ .Values.virtualMachine.features.autoattachSerialConsole }}
              autoattachGraphicsDevice: {{ .Values.virtualMachine.features.autoattachGraphicsDevice }}
              inputs:
              - type: tablet
                bus: virtio
                name: tablet1
              disks:
                {{- range $reg, $props := .Values.disks }}
                {{- if ne "hostDisk" $props.type }}
              - name: {{ $props.name }}
                {{ $props.type }}:
                  bus: {{ $props.bus }}
                  readonly: {{ $props.readonly }}
                bootOrder: {{ $props.bootorder }}
                {{- end }}
                {{- end }}
            resources:
              limits:
                memory: {{ .Values.virtualMachine.machine.memory }}
          terminationGracePeriodSeconds: 0
          volumes:
            {{- range $reg, $props := .Values.disks }}
            {{- if ne "cloudinitvolume" $props.name }}
            {{- if ne "hostDisk" $props.type }}
            {{- if not $props.ephemeral }}
            {{- if not $props.image }}
            - name: {{ $props.name }}
              persistentVolumeClaim:
                claimName: {{ $props.name }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if eq "hostDisk" $props.type }}
            - hostDisk:
                capacity: {{ $props.capacity }}
                path: {{ $props.path }}
                type: {{ $props.type }}
              name: {{ $props.name }}
            {{- end}}
            {{- if $props.image }}
            - containerDisk:
                image: {{ $props.image }}
              name: {{ $props.name }}
            {{- end }}
            {{- if $props.ephemeral }}
            - name: {{ $props.name }}
              ephemeral:
                persistentVolumeClaim:
                  claimName: {{ $props.pvc }}
            {{- end }}
            {{- end }}
            - name: cloudinitvolume
              cloudInitNoCloud:
                userData: |
                  {{- if .Values.cloudinitPath }}
                  {{- $.Files.Get .Values.cloudinitPath | trim | nindent 14 }}
                  {{- else }}
                  #cloud-config
                  hostname: {{ .Values.cloudinit.hostname }}
                  disable_root: {{ .Values.cloudinit.disable_root }}
                  {{- with .Values.cloudinit.network }}
                  network:
                    {{- toYaml . | nindent 20 }}
                  {{- end }}
                  {{- with .Values.cloudinit.groups }}
                  groups:
                    {{- toYaml . | nindent 20 }}
                  {{- end }}
                  users:
                    {{- range $reg, $props := .Values.cloudinit.users }}
                    - name: {{ $props.name }}
                      groups: {{ $props.groups }}
                      sudo: {{ $props.sudo }}
                      shell: {{ $props.shell }}
                      lock_passwd: {{ $props.lock_passwd }}
                      {{- if $props.passwd }}
                      passwd: {{ $props.passwd | quote }}
                      {{- end }}
                      {{- if $props.ssh_import_id }}
                      ssh_import_id:
                        - {{ $props.ssh_import_id }}
                      {{- end }}
                      {{- if $props.ssh_authorized_keys }}
                      ssh_authorized_keys:
                        - {{ $props.ssh_authorized_keys }}
                      {{- end }}
                    {{- end }}
                  {{- with .Values.cloudinit.boot_cmd }}
                  boot_cmd:
                    {{- toYaml . | nindent 20 }}
                  {{- end }}
                  write_files:
                    {{- if .Values.cloudinit.write_as_b64 }}
                    {{- range $reg, $props := .Values.cloudinit.write_files }}
                  - path: {{ $props.path }}
                    permissions: {{ $props.permissions | quote }}
                    content: |
                    {{- $.Files.Get $props.content | trim |b64enc | nindent 22 }}
                    {{- end }}
                    {{- else }}
                    {{- range $reg, $props := .Values.cloudinit.write_files }}
                  - path: {{ $props.path }}
                    permissions: {{ $props.permissions | quote }}
                    content: |
                    {{- $.Files.Get $props.content | trim |nindent 22 }}
                    {{- end }}
                  {{- end }}
                  package_update: {{ .Values.cloudinit.package_update }}
                  package_upgrade: {{ .Values.cloudinit.package_upgrade }}
                  {{- with .Values.cloudinit.packages }}
                  packages:
                    {{- toYaml . | nindent 20 }}
                  {{- end }}
                  {{- with .Values.cloudinit.runcmd }}
                  runcmd:
                  {{- toYaml . | nindent 20 }}
                  {{- end }}
                  {{- end }}
{{- end }}
