apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cdi-operator
    operator.cdi.kubevirt.io: ""
    prometheus.cdi.kubevirt.io: "true"
  name: cdi-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
        prometheus.cdi.kubevirt.io: "true"
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: {{ .Chart.AppVersion }}
        - name: CONTROLLER_IMAGE
          value: quay.io/kubevirt/cdi-controller:{{ .Chart.AppVersion }}
        - name: IMPORTER_IMAGE
          value: quay.io/kubevirt/cdi-importer:{{ .Chart.AppVersion }}
        - name: CLONER_IMAGE
          value: quay.io/kubevirt/cdi-cloner:{{ .Chart.AppVersion }}
        - name: APISERVER_IMAGE
          value: quay.io/kubevirt/cdi-apiserver:{{ .Chart.AppVersion }}
        - name: UPLOAD_SERVER_IMAGE
          value: quay.io/kubevirt/cdi-uploadserver:{{ .Chart.AppVersion }}
        - name: UPLOAD_PROXY_IMAGE
          value: quay.io/kubevirt/cdi-uploadproxy:{{ .Chart.AppVersion }}
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        - name: MONITORING_NAMESPACE
          value: prometheus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: cdi-operator
        ports:
          - name: {{ .Values.service.name }}
            containerPort: {{ .Values.service.port }}
            protocol: {{ .Values.service.protocol }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists

