{{- if eq .Values.serviceAccount.create true}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-init
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name}}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: secret-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
