apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hostname}}-userdata
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
data:
  user-data.yaml: |-
    #cloud-config
    hostname: {{ .Values.hostname }}
    disable_root: {{ .Values.disable_root }}
    {{- with .Values.network }}
    network:
        {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.groups }}
    groups:
        {{- toYaml . | nindent 4 }}
    {{- end }}
    users:
      {{- range $reg, $props := .Values.users }}
      - name: {{ $props.name }}
        groups: {{ $props.groups }}
        sudo: {{ $props.sudo }}
        shell: {{ $props.shell }}
        lock_passwd: {{ $props.lock_passwd }}
        {{- if $props.password }}
        passwd:
        {{- end }}
        {{- range $id := $props.ssh_import_id }}
        ssh_import_id:
          - {{ $id }}
        {{- end }}
        {{- range $key := $props.ssh_authorized_keys }}
        ssh_authorized_keys:
          - {{ $key }}
        {{- end }}
      {{- end }}
    {{- with .Values.boot_cmd }}
    boot_cmd:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if gt (len .Values.write_files) 0 }}
    write_files:
    {{- range $reg, $props := .Values.write_files }}
      - path: {{ $props.path }}
        permissions: {{ $props.permissions | quote }}
      {{- if $props.url }}
        url: {{ $props.url | quote }}
      {{- end}}
      {{- if $props.content }}
        content: |-
          {{ $props.content}}
      {{- end }}
      {{- end }}
    {{- end }}
    package_reboot_if_required: {{ .Values.package_reboot_if_required }}
    package_update: {{ .Values.package_update }}
    package_upgrade: {{ .Values.package_upgrade }}
    {{- with .Values.packages }}
    packages:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.runcmd }}
    runcmd:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.wireguard }}
    wireguard:
      interfaces:
        {{- range $reg, $props := .Values.wireguard.interfaces }}
        - name: {{ $props.name }}
          config_path: {{ $props.config_path }}
        {{- end }}
    {{- end }}
