apiVersion: v1
kind: Service
metadata:
  name: kubevirt-manager
  namespace: kubevirt-manager
  labels:
    app: kubevirt-manager
    kubevirt-manager.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: kubevirt-manager
  ports:
    - name: {{ .Values.service.name }} 
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
