apiVersion: v2
name: kubevirt-manager
description: Install the Kubevirt Manager UI

type: application
version: 0.2.2
appVersion: 1.5.0-rc

maintainers:
  - name: "cloudymax"
    email: "emax@cloudydev.net"
    url: "https://github.com/cloudymax/"
