replicaCount: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 80
  protocol: TCP
  name: http

prometheus: 
  enabled: false
  serviceName: "prometheus-prometheus"
  serviceNamesapce: "prometheus"

ingress:
  enabled: false
  className: "nginx"
  hostname: "kubevirt.domain.com"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls:
    enabled: false
    secretName: "tls-kubevirt-manager"
