# /etc/rancher/k3s/config.yaml
# /etc/rancher/rke2/config.yaml
---
write-kubeconfig-mode: "0600"
cni:
  - cilium
disable:
  - rke2-ingress-nginx
# Internal Network IP
node-ip: 10.1.0.248
bind-address: 10.1.0.248
node-external-ip: 10.1.0.248
advertise-address: 10.1.0.248
tls-san:
  - 192.168.2.70
  - 10.1.0.248
# Required for l2 IP Announcement
disable-kube-proxy: true
kubelet-arg:
- config=/etc/kubernetes/kubelet.yaml
