###############################################################
#  ____ _           _
# / ___| |_   _ ___| |_ ___ _ __
#| |   | | | | / __| __/ _ \ '__|
#| |___| | |_| \__ \ ||  __/ |
# \____|_|\__,_|___/\__\___|_|
#
###############################################################
cluster:
  # -- Name of the cluster to create
  name: capi

  # -- Version of kubernetes to deploy
  version: v1.30.1

  # -- Namespace in which to host cluster components
  namespace: kubevirt

  # -- Cluster internal DNS domain
  dnsDomain: cluster.local

  # -- Disable the deployment of kube-proxy
  disableKubeProxy: false

  # -- CIDR block for pod network
  podCidrBlock: "10.243.0.0/16"

  # -- CIDR block for services
  serviceCidrBlock: "10.95.0.0/16"

  # -- Type of service to use when exposing control plane endpoint on Host
  controlPlaneServiceType: ClusterIP

  # -- Extra args to pass to kubelet
  kubeletExtraArgs:
    kube-reserved: cpu=1,memory=2Gi,ephemeral-storage=1Gi
    system-reserved: cpu=500m,memory=1Gi,ephemeral-storage=1Gi
    eviction-hard: memory.available<500Mi,nodefs.available<10%

###############################################################
# __     ____  __   ____             _
# \ \   / /  \/  | |  _ \ ___   ___ | |___
#  \ \ / /| |\/| | | |_) / _ \ / _ \| / __|
#   \ V / | |  | | |  __/ (_) | (_) | \__ \
#    \_/  |_|  |_| |_|   \___/ \___/|_|___/
###############################################################
MachineTemplates:

  # -- Control Plane VM pool spec
  controlPlane:
    size: 1
    cores: 2
    memory: 4Gi
    disk: 32Gi
    cpuModel: host-passthrough

  # -- Worker VM spec
  workers:
    size: 2
    cores: 4
    memory: 8Gi
    disk: 32Gi
    cpuModel: host-passthrough

###############################################################
# _   _      _              ____ _                _
#| | | | ___| |_ __ ___    / ___| |__   __ _ _ __| |_ ___
#| |_| |/ _ \ | '_ ` _ \  | |   | '_ \ / _` | '__| __/ __|
#|  _  |  __/ | | | | | | | |___| | | | (_| | |  | |_\__ \
#|_| |_|\___|_|_| |_| |_|  \____|_| |_|\__,_|_|   \__|___/
###############################################################
helmCharts:
  # Helm Chart for Cilium CNI
  - name: cilium
    metadata:
      name: clilum
      namespace: kubevirt
    spec:
      repoURL: https://helm.cilium.io/
      chartName: cilium
      namespace: kube-system
      options:
        waitForJobs: true
        wait: true
        install:
          createNamespace: true
      valuesTemplate: |-
        operator:
          replicas: 1
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true

  # Helm Chart for Cert-Manager
  - name: cert-manager
    metadata:
      name: cert-manager
      namespace: kubevirt
    spec:
      repoURL: https://charts.jetstack.io
      chartName: cert-manager
      namespace: cert-manager
      version: v1.16.2
      options:
        install:
          createNamespace: true
      valuesTemplate: |-
        crds:
          enabled: true

  # Helm Chart for ingress-nginx
  - name: ingress-nginx
    metadata:
      name: ingress-nginx
      namespace: kubevirt
    spec:
      repoURL: https://kubernetes.github.io/ingress-nginx
      chartName: ingress-nginx
      namespace: ingress-nginx
      options:
        install:
          createNamespace: true
      valuesTemplate: |-
        install:
          createNamespace: true

