---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  monitorNamespace: {{ .Values.monitorNamespace }}
  monitorAccount: {{ .Values.monitorAccount }}
  configuration:
    permittedHostDevices:
      {{- if .Values.permittedHostDevices.pciHostDevices }}
      {{- with .Values.permittedHostDevices.pciHostDevices }}
      pciHostDevices:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- else }}
      pciHostDevices: []
      {{- end }}
      {{- if .Values.permittedHostDevices.mediatedDevices }}
      {{- with .Values.permittedHostDevices.mediatedDevices }}
      mediatedDevices:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- else }}
      mediatedDevices: []
      {{- end }}
    {{- if .Values.mediatedDevicesTypes }}
    mediatedDevicesConfiguration:
      {{- with .Values.mediatedDevicesTypes}}
      mediatedDevicesTypes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    developerConfiguration:
      useEmulation: {{ .Values.useEmulation }}
      {{- with .Values.featureGates }}
      featureGates:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
