---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubevirt.io: ""
    pod-security.kubernetes.io/enforce: "privileged"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: {{ .Release.Name }}
  name: kubevirt
