---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  controlPlaneServiceTemplate:
    spec:
      type: {{ .Values.cluster.controlPlaneServiceType }}
