---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    capk.cluster.x-k8s.io/template-kind: extra-resource
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
  name: cloud-controller-manager
  namespace: {{ .Values.cluster.namespace }}
