name: Lint and Test Chart

on: pull_request

permissions:
  contents: read

jobs:
  kubevirt:
    name: Kubevirt-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependency chart repos
        run: |
          helm repo add kubevirt https://cloudymax.github.io/kubevirt-community-stack

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create namespace kubevirt 
          ct install --charts charts/kubevirt \
            --namespace kubevirt \
            --target-branch ${{ github.event.repository.default_branch }} \
            

  kubevirtCDI:
    name: KubevirtCDI-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependency chart repos
        run: |
          helm repo add kubevirt https://cloudymax.github.io/kubevirt-community-stack

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Test on k3s
        run: |
          kubectl create namespace kubevirt 
          helm install kubevirt charts/kubevirt --namespace kubevirt --wait

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create namespace cdi
          ct install --charts charts/kubevirt-cdi \
            --namespace cdi \
            --target-branch ${{ github.event.repository.default_branch }}

  kubevirtManager:
    name: KubevirtManager-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependency chart repos
        run: |
          helm repo add kubevirt https://cloudymax.github.io/kubevirt-community-stack

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Test on k3s
        run: |
          kubectl create namespace kubevirt
          kubectl create namespace cdi
          helm install kubevirt charts/kubevirt --namespace kubevirt --wait
          helm install kubevirt charts/kubevirt-cdi --namespace cdi --wait

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create namespace kubevirt-manager
          ct install --charts charts/kubevirt-manager \
            --namespace kubevirt-manager \
            --target-branch ${{ github.event.repository.default_branch }}

  kubevirtVm:
    name: KubevirtVm-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependency chart repos
        run: |
          helm repo add kubevirt https://cloudymax.github.io/kubevirt-community-stack

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'

      - name: Test on k3s
        run: |
          kubectl create namespace kubevirt
          kubectl create namespace cdi
          helm install kubevirt charts/kubevirt --namespace kubevirt --wait
          helm install kubevirt charts/kubevirt-cdi --namespace cdi --wait

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct install --charts charts/kubevirt-vm \
            --namespace kubevirt \
            --target-branch ${{ github.event.repository.default_branch }}
